language: python
python: "2.7"
env:  # These should match the tox env list
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
install: pip install tox coveralls
script: tox
sudo: false
after_success:
    coveralls
